AWSTemplateFormatVersion: 2010-09-09
Description: AZ Parameter demo

Parameters:
  MyKeyName:
    Description: Select the key name from the list
    Type: AWS::EC2::KeyPair::KeyName
  MyAvailabilityZone:
    Description: Select the AZ
    Type: String
    Default: ap-southeast-1a
    AllowedValues:
      - ap-southeast-1a
      - ap-southeast-1b    
      - ap-southeast-1c

Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0e97ea97a2f374e3d
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - default
      AvailabilityZone: !Ref MyAvailabilityZone
      
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: my new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
